### PR TITLE
chore: cleanup and prettify README

### PR DESCRIPTION
**Pull request by mojoaxel**
no content changes just linting

### CODE REVIEW

**Comment by gauravchl** [comment]
Just added you to npm, feel free to release :)

**Comment by mojoaxel** [comment]
> Just added you to npm, feel free to release :)

:tada: :rocket: Thx!

**Comment by mojoaxel** [comment]
@gauravchl It looks like a have to npm rights to publish, yet :confused:

**Comment by gauravchl** [comment]
@mojoaxel How do I do that...I don't see any option other than adding as a maintainer. 
Screen Shot 2019-10-17 at 5 13 51 PM

**Pull request merged**
